version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "8080:3000"
  api:
    build:
      context: ./api
    ports:
      - "8081:3001"
    networks:
      - todo-apuri

networks:
  todo-apuri:
